---

- name: init prod service
  hosts: prod
  become: yes

  tasks:
    - name: Ensure tomcat package is present
      apt:
        name: tomcat
        state: present

- name: init deploy service
  hosts: deploy
  become: yes

  tasks:
  - name: Ensure git package is present
    apt:
      name: git
      state: present

  - name: Ensure jdk package is present
    apt:
      name: default-jdk
      state: present

  - name: Ensure maven package is present
    apt:
      name: maven
      state: present